FROM node:lts-alpine3.16

# Todo: npm install global in dockerfile does not work so node modules are copied apparently
RUN npm install -g npm
COPY ./frontend/mood_classification/package.json /tmp/package.json
COPY ./frontend/mood_classification/package-lock.json /tmp/package-lock.json
RUN cd /tmp && npm install --global