version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.17.7
    container_name: "elasticsearch"
    networks:
      - fullstack
    environment:
      - discovery.type=single-node
    volumes:
      - ./elasticsearch:/opt/
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: kibana:7.17.7
    container_name: "kibana"
    networks:
      - fullstack
    volumes:
      - ./kibana:/opt/
    ports:
      - 5601:5601
  fastapi:
    build:
      context: ./
      dockerfile: ./backend/dockerfile_fastapi
    container_name: fastapi
    networks:
      - fullstack
    volumes:
      - type: bind
        source: ./backend/fastapi
        target: /opt/fastapi
    ports:
      - 8000:8000
    command: sh -c  "cd /opt/fastapi && uvicorn main:app --host 0.0.0.0 --port 8000 --reload "

  react:
    build:
      context: ./
      dockerfile: ./frontend/dockerfile_react
    container_name: react
    networks:
      - fullstack
    volumes:
      - type: bind
        source: ./frontend/mood_classification
        target: /opt/mood_classification
    ports:
      - 3000:3000
    command: sh -c "cd /opt/mood_classification && npm start"

networks:
  fullstack:
    name: text_analytics
    driver: bridge
