FROM alpine:latest

RUN apk add build-base

RUN apk add python3
RUN python3 -m ensurepip --upgrade
RUN python3 -m pip install fastapi[all]
COPY ./backend/requirements.txt /tmp/requirements.txt
RUN python3 -m pip install -r /tmp/requirements.txt

RUN python -m pip install -U pip setuptools wheel
RUN python -m pip install -U spacy
RUN python -m spacy download en_core_web_sm
