FROM ubuntu:latest
RUN apt update -y && apt upgrade -y
RUN apt install gcc python3 python3-pip -y

RUN python3 -m pip install fastapi[all]
COPY ./backend/requirements.txt /tmp/requirements.txt
RUN python3 -m pip install -r /tmp/requirements.txt

RUN python3 -m pip install -U pip setuptools wheel
RUN python3 -m pip install -U spacy
RUN python3 -m spacy download en_core_web_sm
