FROM elasticsearch:7.17.7

RUN apt update -y && apt upgrade -y
RUN apt install python3 -y
RUN apt-get install python3-pip -y

# Copy python scripts and dump if exists
COPY ./elasticsearch/startup.sh /tmp/startup.sh

# get components for elasticdump
# update repo because otherwise installation of node/npm requires numerical input which I cannot automate
RUN curl -fsSL https://deb.nodesource.com/setup_14.x | bash - &&  apt update -y && apt install -y nodejs
RUN npm install elasticdump --global --save

# use this script later to ensure elasticsearch is running 
RUN chmod 777 /tmp/startup.sh
RUN chown elasticsearch:elasticsearch /tmp/startup.sh

COPY ./elasticsearch/requirements.txt /tmp/requirements.txt
RUN pip3 install -r /tmp/requirements.txt
Entrypoint  ["/bin/tini", "--", "/tmp/startup.sh"]

